Make Tagit labels clickable links for id.kb.se keywords
Kungbib/idkbse-ojs-plugin pull request #1
Opened 2021-05-10 13:29 UTC by lrosenstrom

2021-05-10 14:53 UTC, olovy commented on IdkbsePlugin.inc.php
> +				var prefLabel = decodeURIComponent(ui.tagLabel.split(\"/\").pop());
Move inside `if` statement below?

2021-05-10 15:00 UTC, olovy requested changes
I think we need to get prefLabel from the data (and not from the URI) since e.g. SSIF terms won't have the prefLabel in the URI.

What happens to `label` and `value` returned from `tagSource? Aren't they avaliable to use in `beforeTagAdded`?

2021-05-11 06:41 UTC, lrosenstrom commented
'value' is available in beforeTagAdded, but the variable name is 'tagLabel', so id = ui.tagLabel gets the value of 'value' in tagSource. 
We can put both preflabel and the uri in 'value' and parse the preflabel. In that way we can be sure the preflabel is always correct. The downside with such an approach is that the keywords will show up as 'preflabel|uri' in other views in OJS, and that the OAI-PMH plugin will need more special handling for keyword forms: instead of just dealing with keywords in forms of different URIs it will also need to handle the preflabel/ special characters / uri combo that is specific to this plugin. But I guess we have to go down that path to get the preflabel part right!

2021-05-11 07:16 UTC, lrosenstrom commented
Updated the PR after feedback. Another plus with the new approach is that browsing the autocompleted keywords with the keyboard is clearer now that you see the prefLabel before the URI.

2021-05-11 14:13 UTC, olovy approved these changes
LGTM!

2021-05-11 14:14 UTC, olovy commented on IdkbsePlugin.inc.php
>  				}
Indent one step?

2021-05-12 10:57 UTC, merged